#ifndef MANAGEOUTPUTPROFILESDIALOG_H
#define MANAGEOUTPUTPROFILESDIALOG_H

#include <QDialog>
#include <QList>
#include <platemaker/models/output_profile.hpp>

namespace Ui {
class ManageOutputProfilesDialog;
}

/**
 * @brief The ManageOutputProfilesDialog class provides a dialog for managing output profiles.
 * It allows users to view, create, edit, duplicate, delete, and set the active output profile. 
 * The dialog displays a list of profiles and provides buttons for various actions.
 */
class ManageOutputProfilesDialog : public QDialog
{
    Q_OBJECT

public:
    explicit ManageOutputProfilesDialog(QWidget *parent = nullptr); //< Constructs the dialog and initializes the UI.
    ~ManageOutputProfilesDialog() override;                         //< Destroys the dialog and cleans up resources.

    /**
     * @brief Populates the list of output profiles before calling exec().
     * @param profiles The list of output profiles to display.
     * @param activeProfileName The name of the currently active profile.
     */
    void setProfiles(const QList<Platemaker::Models::OutputProfile> &profiles,
                     const QString &activeProfileName);

    /**
     * @brief Retrieves the updated list of output profiles after the dialog is accepted.
     * @return The list of output profiles.
     */
    QList<Platemaker::Models::OutputProfile> profiles() const;
    QString activeProfileName() const;                        //!< Retrieves the name of the currently active profile after the dialog is accepted.

private slots:
    void onSelectionChanged();      //!< Slot for when the selection in the profile list changes. Updates button states accordingly.
    void onNewClicked();            //!< Slot for when the "New" button is clicked. Opens the OutputProfileDialog to create a new profile.
    void onEditClicked();           //!< Slot for when the "Edit" button is clicked. Opens the OutputProfileDialog to edit the selected profile.
    void onDuplicateClicked();      //!< Slot for when the "Duplicate" button is clicked. Duplicates the selected profile and adds it to the list.
    void onDeleteClicked();         //!< Slot for when the "Delete" button is clicked. Deletes the selected profile after confirmation.
    void onSetActiveClicked();      //!< Slot for when the "Set Active" button is clicked. Sets the selected profile as the active one.

private:
    void rebuildList();             //!< Rebuilds the list widget to reflect the current profiles and active profile. Called after any changes to the profiles.
    void updateButtonStates();      //!< Updates the enabled/disabled state of the buttons based on the current selection and profile list.
    int  selectedRow() const;       //!< Returns the index of the currently selected row in the profile list, or -1 if no selection.

    Ui::ManageOutputProfilesDialog *ui;       //!< The UI form generated by Qt Designer (ui_manageoutputprofilesdialog.h).

    QList<Platemaker::Models::OutputProfile> m_profiles;    //!< The list of output profiles being managed in the dialog.
    QString                  m_activeProfileName;           //!< The name of the currently active output profile.
};

#endif // MANAGEOUTPUTPROFILESDIALOG_H
