#ifndef IMAGETILE_H
#define IMAGETILE_H

#include <QPixmap>
#include <QWidget>

#include <platemaker/models/project_item.hpp>

namespace Ui { class imagetile; }

/**
 * @brief The ImageTile class represents a single image tile in the UI.
 * It displays the image thumbnail, filename, and status, and provides buttons
 * to move the tile up or down in a list. The tile can asynchronously load
 * its thumbnail from a cache directory.
 */
class ImageTile : public QWidget
{
    Q_OBJECT

public:
    explicit ImageTile(QWidget *parent = nullptr);  //!< Constructs the image tile widget and initializes the UI.
    ~ImageTile();                                   //!< Destroys the image tile widget and cleans up resources.

    /**
     * @brief Sets the file information for the image tile.
     * @param filePath The path to the image file.
     * @param status The status of the file.
     * @param cacheDir The directory where thumbnails are cached.
     */
    void setFileInfo(const QString& filePath,
                     Platemaker::Models::FileStatus status,
                     const QString& cacheDir);

    void setThumbnail(const QPixmap& pixmap);   //!< Sets the thumbnail image for the tile. The pixmap is scaled to fit within the fixed label area while maintaining aspect ratio.

    /**
     * @brief Sets the name of the image tile.
     * UNUSED. Legacy code may have used this to set the label text, but now it is primarily for display purposes. The name is typically derived from the file path.
     * @param name The name to set.
     */
    void setTileName(const QString& name);

signals:
    // Emitted by the ▲/▼ buttons; the tile identifies itself by its file path.
    void moveUpRequested(const QString& filePath);
    void moveDownRequested(const QString& filePath);

private:
    void updateStatusStyle(Platemaker::Models::FileStatus status);  //!< Updates the visual style of the tile based on the file status (e.g., color coding for different statuses).
    void loadThumbnailAsync(const QString& cacheDir);               //!< Asynchronously loads the thumbnail from the cache directory to avoid blocking the UI.

    Ui::imagetile* ui;      //!< Pointer to the UI form generated by Qt Designer (ui_imagetile.h).
    QString m_filePath;     //!< The file path associated with this image tile, used to identify the tile in signals and for thumbnail loading.
};

#endif // IMAGETILE_H
