#ifndef OUTPUTFORMATOPTIONSWIDGET_H
#define OUTPUTFORMATOPTIONSWIDGET_H

#include <QWidget>

#include <platemaker/models/output_profile.hpp>

namespace Ui { class OutputFormatOptionsWidget; }

/**
 * @brief Reusable editor for an OutputProfile's image format + per-format encoding
 *        options (PNG / JPEG / WebP).
 *
 * A format dropdown reveals exactly one options group. The single source of truth
 * for the model↔widget mapping (incl. the JPEG subsampling enum↔index), embedded in
 * both the project Output tab and OutputProfileDialog.
 */
class OutputFormatOptionsWidget : public QWidget
{
    Q_OBJECT

public:
    explicit OutputFormatOptionsWidget(QWidget* parent = nullptr);      //!< Constructs the widget and initializes the UI.
    ~OutputFormatOptionsWidget() override;                              //!< Destroys the widget and cleans up resources.

    /**
     * @brief Load the format + all option structs from \p profile (does not emit edited()).
     * Call before exec() to populate fields when editing an existing profile.
     * @param profile The profile to be loaded into the widget.
     */
    void setFromProfile(const Platemaker::Models::OutputProfile& profile);

    /**
     * @brief Write the format + all option structs into \p profile (name/slicing untouched).
     * @param profile The profile into which to write the format and options.
     */
    void applyToProfile(Platemaker::Models::OutputProfile& profile) const;

signals:
    void edited();                  //!< any control changed by the user

private slots:
    void onFormatChanged();         //!< Slot for when the output format dropdown changes. Updates the visibility of the option groups accordingly.
    void onAnyOptionChanged();      //!< Slot for when any of the option controls change. Emits the edited() signal if not currently loading from a profile.

private:
    void updateVisibility();        //!< Show/hide the option groups based on the selected output format.

    Ui::OutputFormatOptionsWidget* ui;  //!< The UI form generated by Qt Designer (ui_outputformatoptionswidget.h).
    bool m_loading = false;             //!< suppresses edited() while setFromProfile() runs
};

#endif // OUTPUTFORMATOPTIONSWIDGET_H
