#ifndef CANVASPROFILEDIALOG_H
#define CANVASPROFILEDIALOG_H

#include <QDialog>
#include <QColor>
#include <platemaker/models/canvas_profile.hpp>

namespace Ui {
class CanvasProfileDialog;
}

/**
 * @brief The CanvasProfileDialog class provides a dialog for creating or editing canvas profiles.
 * It allows users to specify the name, dimensions, margins, visual colour, and background colour
 * of a canvas profile. The dialog also provides a live preview of the canvas based on the current settings.
 */
class CanvasProfileDialog : public QDialog
{
    Q_OBJECT

public:
    explicit CanvasProfileDialog(QWidget *parent = nullptr);    //!< Constructs the dialog and initializes the UI.

    /**
     * @brief Sets the profile to be edited in the dialog. 
     * Call before exec() to populate fields when editing an existing profile.
     * Leave uncalled (or call with default-constructed profile) for a new profile.
     * @param profile The profile to be edited.
     */
    void setProfile(const Platemaker::Models::CanvasProfile &profile);

    /**
     * @brief Retrieves the profile filled in the dialog.
     * Call after exec() == Accepted to retrieve the filled-in profile.
     * @return The edited profile.
     */
    Platemaker::Models::CanvasProfile profile() const;

    ~CanvasProfileDialog() override;    //!< Destroys the dialog and cleans up resources.

protected:
    bool eventFilter(QObject *watched, QEvent *event) override; // Intercepts paint events for the canvas preview widget to draw the live preview.

private slots:
    void onSaveClicked();                       //!< Slot for when the Save button is clicked. Validates input and accepts the dialog if valid.
    void onPickVisualColour();                  //!< Slot for when the Visual Colour button is clicked. Opens a QColorDialog to pick a colour.
    void onPickBgColour();                      //!< Slot for when the Background Colour button is clicked. Opens a QColorDialog to pick a colour.
    void onDimensionsChanged();                 //!< Slot for when any of the dimension spin boxes change. Updates the preview and size info label.
    void onSafeAreaModeToggled(bool checked);   //!< Slot for when the Safe Area Mode radio button is toggled. Updates the preview and size info label.

private:
    void applyColourToButton(QPushButton *button, const QColor &colour);    //!< Applies the given colour to the specified button's background.
    void updatePreview();               //!< Updates the canvas preview widget to reflect the current settings.
    void updateSizeInfoLabel();         //!< Updates the text label showing the absolute size or work area size based on current settings.
    void paintCanvasPreview();          //!< Paints the canvas preview widget with the current settings (called from eventFilter on paint events).

    Ui::CanvasProfileDialog *ui;        //<! The UI form generated by Qt Designer (ui_canvasprofiledialog.h).

    QColor m_visualColour;              //!< The visual/margin colour selected in the dialog.
    QColor m_bgColour;                  //!< The background colour selected in the dialog.
    bool   m_safeAreaMode = false;      //!< Whether the dialog is in safe-area mode (true) or absolute size mode (false).
};

#endif // CANVASPROFILEDIALOG_H
