#ifndef OUTPUTPROFILEDIALOG_H
#define OUTPUTPROFILEDIALOG_H

#include <QDialog>
#include <platemaker/models/output_profile.hpp>

namespace Ui {
class OutputProfileDialog;
}
class OutputFormatOptionsWidget;

/**
 * @brief The OutputProfileDialog class provides a dialog for creating or editing output profiles.
 * It allows users to specify the name, output format, per-format encoding options, slicing parameters,
 * and last slice policy of an output profile. The dialog uses a shared OutputFormatOptionsWidget for
 * editing the format and its options.
 */
class OutputProfileDialog : public QDialog
{
    Q_OBJECT

public:
    explicit OutputProfileDialog(QWidget *parent = nullptr);        //!< Constructs the dialog and initializes the UI.
    ~OutputProfileDialog() override;                                //!< Destroys the dialog and cleans up resources.

    /**
     * @brief Sets the profile to be edited in the dialog. 
     * Call before exec() to populate fields when editing an existing profile.
     * Leave uncalled (or call with default-constructed profile) for a new profile.
     * @param profile The profile to be edited.
     */
    void setProfile(const Platemaker::Models::OutputProfile &profile);
    Platemaker::Models::OutputProfile profile() const;              //!< Retrieves the profile filled in the dialog. Call after exec() == Accepted to retrieve the filled-in profile.

private slots:
    void onSaveClicked();                                   //!< Slot for when the Save button is clicked. Validates input and accepts the dialog if valid.

private:
    Ui::OutputProfileDialog *ui;                            //!< The UI form generated by Qt Designer (ui_outputprofiledialog.h).
    OutputFormatOptionsWidget* m_formatOptions = nullptr;   //!< Shared widget for editing the output format and its per-format encoding options.
};

#endif // OUTPUTPROFILEDIALOG_H
