#ifndef MANAGECANVASPROFILESDIALOG_H
#define MANAGECANVASPROFILESDIALOG_H

#include <QDialog>
#include <QList>
#include <platemaker/models/canvas_profile.hpp>

namespace Ui {
class ManageCanvasProfilesDialog;
}

/**
 * @brief The ManageCanvasProfilesDialog class provides a dialog for managing canvas profiles.
 * It allows users to view, create, edit, duplicate, delete, and set the active canvas profile. 
 * The dialog displays a list of profiles and provides buttons for various actions.
 */
class ManageCanvasProfilesDialog : public QDialog
{
    Q_OBJECT

public:
    explicit ManageCanvasProfilesDialog(QWidget *parent = nullptr); //< Constructs the dialog and initializes the UI.
    ~ManageCanvasProfilesDialog() override;                         //< Destroys the dialog and cleans up resources.

    /**
     * @brief Populates the list of canvas profiles before calling exec().
     * @param profiles The list of canvas profiles to display.
     * @param activeProfileName The name of the currently active profile.
     */
    void setProfiles(const QList<Platemaker::Models::CanvasProfile> &profiles,
                     const QString &activeProfileName);

    /**
     * @brief Retrieves the updated list of canvas profiles after the dialog is accepted.
     * @return The list of canvas profiles.
     */
    QList<Platemaker::Models::CanvasProfile> profiles() const;
    QString activeProfileName() const;                              //!< Retrieves the name of the currently active profile after the dialog is accepted.

signals:
    /**
     * @brief Emitted when the user clicks "Generate templates from active".
     * Connect in MainWindow to trigger the actual generation.
     * @param activeProfile The active canvas profile.
     */
    void generateTemplatesRequested(const Platemaker::Models::CanvasProfile &activeProfile);

private slots:
    void onSelectionChanged();          //!< Slot for when the selection in the profile list changes. Updates button states accordingly.
    void onNewClicked();                //!< Slot for when the "New" button is clicked. Opens the CanvasProfileDialog to create a new profile.
    void onEditClicked();               //!< Slot for when the "Edit" button is clicked. Opens the CanvasProfileDialog to edit the selected profile.
    void onDuplicateClicked();          //!< Slot for when the "Duplicate" button is clicked. Duplicates the selected profile and adds it to the list.
    void onDeleteClicked();             //!< Slot for when the "Delete" button is clicked. Deletes the selected profile after confirmation.
    void onSetActiveClicked();          //!< Slot for when the "Set Active" button is clicked. Sets the selected profile as the active one.
    void onGenerateTemplatesClicked();  //!< Slot for when the "Generate Templates" button is clicked. Emits a signal to request template generation for the selected profile.

private:
    void rebuildList();             //!< Rebuilds the list widget to reflect the current profiles and active profile. Called after any changes to the profiles.
    void updateButtonStates();      //!< Updates the enabled/disabled state of the buttons based on the current selection and profile list.
    int  selectedRow() const;       //!< Returns the index of the currently selected row in the profile list, or -1 if no selection.

    Ui::ManageCanvasProfilesDialog *ui;     //!< Pointer to the UI form generated by Qt Designer (ui_managecanvasprofilesdialog.h).

    QList<Platemaker::Models::CanvasProfile> m_profiles;    //!< The list of canvas profiles being managed in the dialog.
    QString                  m_activeProfileName;           //!< The name of the currently active profile, used to mark it in the list and for template generation.
};

#endif // MANAGECANVASPROFILESDIALOG_H
